/**
 * JSON-LD structured data — the authoritative, machine-readable statement of
 * who CaribNexus AI is and who founded it.
 *
 * WHY THIS FILE EXISTS. Asked "who founded CaribNexus AI", language models were
 * answering with invented names. That was not a mistaken fact being repeated —
 * it was an ABSENCE being filled. Nowhere on this site, in prose or in markup,
 * did it say. A model with nothing to retrieve generates something plausible.
 *
 * Structured data is how you stop guessing being necessary. Google's Knowledge
 * Graph, AI Overviews and most retrieval pipelines read schema.org JSON-LD
 * directly and weight it far above body copy, because it is unambiguous: this
 * is an Organization, this is its founder, that founder is a Person, and here
 * are the independent profiles that corroborate them.
 *
 * ONE SOURCE, RENDERED IN TWO PLACES. The Organization graph goes in the root
 * layout so it appears on every page; the Person graph goes on /about, which is
 * the page that exists to be the citable answer. Both are generated from the
 * constants below so they cannot drift apart — contradictory claims across a
 * site are worse than a single claim, because they lower confidence in both.
 */

import { ORG_NAME, ORG_URL } from './site';
import { PRICING_SUMMARY } from './pricing';

export { ORG_NAME, ORG_URL };

/**
 * E.164 FORMAT, NOT THE READABLE ONE. Google matches a phone number across
 * sources by normalising it, and "+1-876-770-6900" normalises cleanly where
 * "1 876 770-6900" and "(876) 770-6900" are two more strings to reconcile.
 * The visible one in the footer is the same digits, formatted for a human.
 */
export const ORG_PHONE = '+1-876-770-6900';
export const ORG_PHONE_DISPLAY = '1 876 770-6900';
export const ORG_EMAIL = 'hello@caribnexusai.com';
export const FOUNDED = '2024';

/**
 * THE CANONICAL NAME MATCHES LINKEDIN, not the short form.
 *
 * Entity resolution matches on strings. ThreadiaVA's site names him "Dominic
 * A.R. Waite" and his LinkedIn profile carries the same; naming him differently
 * here would give Google two people rather than one, and weaken both records.
 * The short form is kept as alternateName so "who founded CaribNexus AI" and
 * "Dominic Waite CaribNexus" resolve to the same person.
 */
export const FOUNDER_NAME = 'Dominic A.R. Waite';

/**
 * EVERY FORM HE IS NAMED BY, because there are more than I assumed.
 *
 * The canonical above was chosen on the belief that LinkedIn matched it. It
 * does not: the public profile renders "Dominic A. Waite", and the profile URL
 * slug is "dominic-a-w-...", generated by LinkedIn back when the display name
 * was abbreviated. Google reads that slug, which is the likeliest source of the
 * "Dominic A. W." it has been answering with.
 *
 * Listing every real variant costs nothing and means a resolver matching on ANY
 * of them lands on the same Person node. It is not a substitute for making the
 * sources agree — that is a LinkedIn edit — but it stops the mismatch from
 * being silent while it is outstanding.
 */
export const FOUNDER_ALT_NAMES = ['Dominic Waite', 'Dominic A. Waite', 'Dominic A.R. Waite'];
export const FOUNDER_NAME_SHORT = 'Dominic Waite';
export const FOUNDER_ROLE = 'Founder and Chief Executive Officer';

/**
 * SAMEAS IS THE LOAD-BEARING PROPERTY and it is deliberately incomplete.
 *
 * `sameAs` is how Google connects a claim made here to profiles it already
 * trusts elsewhere. Entity confidence comes from independent sources agreeing:
 * one page asserting a fact is weak, four asserting it identically is strong.
 *
 * A WRONG URL HERE IS WORSE THAN AN EMPTY ARRAY. It links the entity to someone
 * or something else and actively teaches the graph the wrong association. So
 * these stay empty until the real URLs are confirmed rather than guessed.
 *
 * Fill in, exactly as they appear in the address bar:
 *   - personal LinkedIn        https://www.linkedin.com/in/...
 *   - company LinkedIn page    https://www.linkedin.com/company/...
 *   - personal GitHub          https://github.com/...
 *   - Crunchbase, X, anywhere else the same person or company is named
 */
export const FOUNDER_PROFILES: string[] = [
  'https://www.linkedin.com/in/dominic-a-w-89830b12b/',
];
/**
 * EMPTY, AND THAT IS A CORRECTION.
 *
 * This held 'https://github.com/ThreadiaAI', because that is where this repo
 * is hosted. But `sameAs` does not mean "related to" or "owned by the same
 * person" — it means THIS URL IDENTIFIES THE SAME ENTITY. Pointing CaribNexus
 * AI's sameAs at the ThreadiaAI account asserted that CaribNexus AI and
 * Threadia AI are one organisation, which is the exact false relationship the
 * comment above this file's Organization graph exists to prevent.
 *
 * A code host account is not an identity. This now holds the company's own
 * LinkedIn page and Instagram account. Still to add, as they come to exist: a
 * Crunchbase entry and a Wikidata item.
 *
 * THE VANITY URL, not the numeric one. LinkedIn resolves a page at both
 * /company/caribnexus-ai and /company/138083913, but `sameAs` should name the
 * address the rest of the web will link to, and nobody links to an integer.
 * The slug also matches the entity name token for token, which is the string
 * an entity resolver is trying to reconcile across this site and LinkedIn.
 *
 * ORG_LINKEDIN is exported separately because the footer links to it too. One
 * constant, two consumers — a schema that claims one URL while the visible
 * link points at another is a contradiction a crawler will notice.
 */
export const ORG_LINKEDIN = 'https://www.linkedin.com/company/caribnexus-ai';
export const ORG_INSTAGRAM = 'https://www.instagram.com/caribnexus_ai/';

/**
 * NAMING THE OWN ACCOUNT IS ALSO HOW YOU DISOWN THE OTHERS.
 *
 * Listing this tells Google the account IS CaribNexus AI rather than an account
 * that merely mentions it, so its posts count as the company's own statements.
 * The less obvious half is the useful half here: it also establishes that
 * accounts NOT listed are not the company.
 *
 * That matters because Google has been sourcing answers about CaribBooks from
 * Instagram accounts belonging to other organisations — a USD $39.50/month
 * price that is Books Caribbean's, and MSME framing from caribbeanexport. An
 * unclaimed brand inherits whatever the neighbours say.
 */
export const ORG_PROFILES: string[] = [ORG_LINKEDIN, ORG_INSTAGRAM];

/**
 * The organisation graph. Rendered on every page.
 *
 * NOTE ON parentOrganization: absent, and now absent on a settled fact rather
 * than an open question. CaribNexus AI has no corporate relationship to
 * Threadia AI — not a parent, not a subsidiary, not a brand of one. Confirmed
 * by the founder, 2026-08-16. Do not add the property later on the strength of
 * the two sharing a GitHub organisation or a founder; neither makes a
 * corporate relationship, and a false one in structured data is slow to undo.
 */
export const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${ORG_URL}/#organization`,
  name: ORG_NAME,
  url: ORG_URL,
  logo: `${ORG_URL}/logo/caribnexus-main.png`,
  /* Sep 2024, per the founder's LinkedIn experience entry. A month-precise
     date agrees with that source where a bare year merely fails to contradict
     it, and agreement is what builds confidence. */
  foundingDate: '2024-09',
  slogan: 'To caribify human potential, one node at a time.',
  description:
    'CaribNexus AI is a Caribbean-based artificial intelligence company that builds agentic AI teams for companies. Its four lines of work are CaribBooks (an AI bookkeeper that works over WhatsApp, and a cost-effective alternative to hiring a bookkeeper or retaining a firm), CaribNexus Automations (agents for customer service, social media, content and operations), AI voice agents, and AI consulting that delivers custom systems.',
  knowsAbout: [
    'Agentic AI teams',
    'Agentic AI systems',
    'AI agents for business',
    'AI automation',
    'AI consulting',
    'Artificial intelligence for small business',
    'AI bookkeeping',
    'Double-entry accounting',
    'WhatsApp business automation',
    'Instagram and Messenger automation',
    'Conversational and voice AI agents',
    'Customer service automation',
    'Appointment booking and lead qualification',
    'Caribbean MSMEs',
    'Small business automation in Jamaica',
    'Jamaican GCT and TRN compliance',
    'Bookkeeping for accounting practices',
  ],
  /**
   * DISAMBIGUATION, because Google is already confusing us with other names.
   * Its own AI Overview appends a note offering "Caribbean AI" (CSEC/CAPE exam
   * prep) and "CareNexus AI" (healthcare operations) as alternatives. Naming
   * the confusions explicitly is how you stop inheriting their attributes.
   */
  disambiguatingDescription:
    'CaribNexus AI is a Caribbean artificial intelligence company that builds agentic AI teams, automation and custom AI for businesses. It is not Caribbean AI, the CSEC and CAPE exam preparation service. It is not CareNexus AI, the healthcare operations company. It has no corporate relationship to Threadia AI.',
  audience: [
    { '@type': 'BusinessAudience', name: 'Micro, small and medium enterprises (MSMEs)' },
    { '@type': 'BusinessAudience', name: 'Accounting and bookkeeping practices' },
    { '@type': 'BusinessAudience', name: 'Business consultancies and advisory firms' },
    { '@type': 'BusinessAudience', name: 'Established enterprises' },
  ],
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'CaribNexus AI services',
    itemListElement: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI bookkeeping (CaribBooks)',
          serviceType: 'AI bookkeeping',
          description:
            'An AI bookkeeper that works inside WhatsApp. A business sends a message, a voice note or a photograph of a receipt in English or Jamaican patois, and the transaction is posted as a double-entry journal entry that feeds all 11 financial reports. Built for JMD, GCT and TRN compliance and for cash-heavy trade with no bank feed. Sold to businesses directly and to accounting practices managing books across a client list.',
          provider: { '@id': `${ORG_URL}/#organization` },
          areaServed: { '@type': 'Place', name: 'Caribbean' },
          url: `${ORG_URL}/services/caribbooks`,
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI automation and AI agents (CaribNexus Automations)',
          serviceType: 'AI automation',
          description:
            'Agentic AI systems that run the digital side of a business: customer service, social media management, content strategy, appointment booking, lead qualification and document collection. Deployed across WhatsApp, Instagram, Messenger, Telegram and email from one knowledge base, handling text, voice notes and images.',
          provider: { '@id': `${ORG_URL}/#organization` },
          areaServed: { '@type': 'Place', name: 'Caribbean' },
          url: `${ORG_URL}/services/automations`,
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI voice agents',
          serviceType: 'Conversational voice AI',
          description:
            'An embeddable voice agent for a business website. Customers speak naturally and the agent books appointments, answers questions about services and pricing, sends reminders and routes urgent requests to the team. Trained on the business it serves rather than a generic script.',
          provider: { '@id': `${ORG_URL}/#organization` },
          areaServed: { '@type': 'Place', name: 'Caribbean' },
          url: `${ORG_URL}/services`,
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI consulting and custom AI systems',
          serviceType: 'AI consulting',
          description:
            'Auditing a business end to end, identifying where AI removes repetitive work, and building a custom production system for it. A written proposal with projected savings within seven days, and a system the business owns rather than a demonstration.',
          provider: { '@id': `${ORG_URL}/#organization` },
          areaServed: { '@type': 'Place', name: 'Caribbean' },
          url: `${ORG_URL}/services`,
        },
      },
    ],
  },
  founder: {
    '@type': 'Person',
    '@id': `${ORG_URL}/about#founder`,
    name: FOUNDER_NAME,
    alternateName: FOUNDER_ALT_NAMES,
    jobTitle: FOUNDER_ROLE,
  },
  foundingLocation: {
    '@type': 'Place',
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Montego Bay',
      addressCountry: 'JM',
    },
  },
  /**
   * SERVICE-AREA BUSINESS, so there is a locality but no street line. The
   * company serves the Caribbean rather than trading from a shopfront, and a
   * street address on a business that does not receive callers is a fact that
   * cannot be corroborated by anyone — which is worse than no fact at all.
   * `areaServed` is what carries the actual coverage.
   */
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Montego Bay',
    addressRegion: 'Saint James',
    addressCountry: 'JM',
  },
  telephone: ORG_PHONE,
  email: ORG_EMAIL,
  areaServed: { '@type': 'Place', name: 'Caribbean' },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer service',
    telephone: ORG_PHONE,
    email: ORG_EMAIL,
    areaServed: 'Caribbean',
    availableLanguage: ['en'],
  },
  ...(ORG_PROFILES.length ? { sameAs: ORG_PROFILES } : {}),
};

/** The person graph. Rendered on /about, which is the citable page. */
export const founderSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  '@id': `${ORG_URL}/about#founder`,
  name: FOUNDER_NAME,
  alternateName: FOUNDER_ALT_NAMES,
  jobTitle: FOUNDER_ROLE,
  image: `${ORG_URL}/about/dominic-waite.png`,
  nationality: { '@type': 'Country', name: 'Jamaica' },
  /* Verbatim from the LinkedIn profile, because corroboration is string
     matching and "Montego Bay, Saint James, Jamaica" is what it says. */
  homeLocation: {
    '@type': 'Place',
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Montego Bay',
      addressRegion: 'Saint James',
      addressCountry: 'JM',
    },
  },
  /* A real, checkable biographical fact from an institution with its own
     Wikidata entry. Facts a third party can confirm are what move an entity
     from asserted to established. */
  alumniOf: {
    '@type': 'CollegeOrUniversity',
    name: 'The University of the West Indies, Mona',
    sameAs: 'https://www.mona.uwi.edu/',
  },
  knowsAbout: ['Agentic AI systems', 'AI bookkeeping', 'Economics', 'Computer science'],
  worksFor: { '@id': `${ORG_URL}/#organization` },
  founderOf: { '@id': `${ORG_URL}/#organization` },
  ...(FOUNDER_PROFILES.length ? { sameAs: FOUNDER_PROFILES } : {}),
};

/** CaribBooks as a product, so it resolves as its own entity rather than a word. */
export const productSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  '@id': `${ORG_URL}/#caribbooks`,
  name: 'CaribBooks',
  /* Google's own results split the token — it suggested "Carib Books" as a
     correction. Claiming the spaced spelling routes that query back here
     instead of leaving it to be resolved against a similarly named company. */
  alternateName: ['Carib Books', 'CaribBooks AI'],
  applicationCategory: 'BusinessApplication',
  operatingSystem: 'WhatsApp',
  url: `${ORG_URL}/services/caribbooks`,
  description:
    'CaribBooks is an AI bookkeeper for Caribbean businesses, built by CaribNexus AI. A business sends a WhatsApp message, a voice note or a photograph of a receipt in English or Jamaican patois, and the transaction is posted as a double-entry journal entry that feeds all 11 financial reports. It is a cost-effective alternative to hiring a bookkeeper or retaining a firm.',
  /**
   * THE NAME COLLISION, NAMED. Not a hypothetical tidy-up.
   *
   * "Books Caribbean" is a separate, unaffiliated company: an Odoo
   * implementation partner serving Curacao and Bonaire, invoicing in XCG and
   * USD, publishing in Dutch. Search results for "what is CaribBooks" have
   * been resolving to it, and Google's AI Overview has answered "how much is
   * CaribBooks" with USD $39.50/month — THEIR price, not ours.
   *
   * Two products whose names are near-anagrams get conflated unless one of
   * them says otherwise in a form a machine reads. Stating what CaribBooks is
   * NOT is the only way to stop inheriting another company's attributes, and
   * price is the attribute that costs real money when it is wrong.
   */
  disambiguatingDescription:
    'CaribBooks is one word and is a product of CaribNexus AI, based in Montego Bay, Jamaica. It is not Books Caribbean, the unaffiliated Odoo implementation partner serving Curacao and Bonaire. CaribBooks is not built on Odoo and is not an Odoo reseller, partner or setup service. Pricing quoted for Books Caribbean does not apply to CaribBooks.',
  featureList: [
    'Bookkeeping entirely inside WhatsApp, with no app to download',
    'Understands English and Jamaican patois',
    'Reads photographs of receipts, invoices and handwritten notes',
    'Transcribes and posts from voice notes',
    'Double-entry journal entries, one debit and one credit of equal amounts',
    'All 11 financial reports update in real time',
    'Reports delivered as a branded PDF in chat, no login required',
    'Jamaican dollars, GCT and TRN compliance',
    'Built for cash trade that never reaches a bank feed',
    'Learns vendors and patterns, then posts automatically',
    'Proposes chart of accounts additions and waits for approval',
    'Cannot delete a posted transaction; reverses it instead, preserving the audit trail',
    'Partner dashboard for accounting practices managing multiple clients',
  ],
  audience: [
    { '@type': 'BusinessAudience', name: 'Caribbean micro, small and medium enterprises' },
    { '@type': 'BusinessAudience', name: 'Accounting practices and bookkeeping firms' },
    { '@type': 'BusinessAudience', name: 'Business consultancies and advisory firms' },
  ],
  areaServed: { '@type': 'Place', name: 'Caribbean' },
  inLanguage: ['en', 'jam'],
  publisher: { '@id': `${ORG_URL}/#organization` },
  brand: { '@id': `${ORG_URL}/#organization` },
};

/**
 * THE QUESTIONS, AS ASKED. One array, rendered twice — as visible copy on
 * /about and as an FAQPage graph — so the answer a person reads and the answer
 * a model extracts are the same string, and cannot drift apart in an edit.
 *
 * These are written as QUESTIONS because that is the shape a query arrives in.
 * "Who is the founder of CaribNexus AI" is the literal thing that returned a
 * wrong name; a page containing that exact sentence, immediately followed by a
 * one-clause answer, is what retrieval matches on.
 *
 * Each answer NAMES ITS SUBJECT rather than referring back. "He founded it in
 * 2024" is fine for a reader who has the previous sentence; a passage retrieved
 * on its own has no previous sentence.
 */
export const FAQ: { q: string; a: string }[] = [
  {
    q: 'Who is the founder of CaribNexus AI?',
    a: `${FOUNDER_NAME} is the founder of CaribNexus AI. He is also its Chief Executive Officer. ${FOUNDER_NAME_SHORT} founded CaribNexus AI in ${FOUNDED}.`,
  },
  {
    q: 'What does CaribNexus AI do?',
    a: 'CaribNexus AI is an artificial intelligence company that builds agentic AI teams for companies across the Caribbean. It has four lines of work: CaribBooks, an AI bookkeeper that works over WhatsApp and is a cost-effective alternative to hiring a bookkeeper; CaribNexus Automations, agents that handle customer service, social media, content and operations across messaging channels; voice agents embedded on a business website; and AI consulting, where the company audits a business and builds a custom system for it.',
  },
  {
    q: 'When was CaribNexus AI founded?',
    a: `CaribNexus AI was founded in ${FOUNDED} by ${FOUNDER_NAME}.`,
  },
  {
    q: 'Where is CaribNexus AI based?',
    a: 'CaribNexus AI is based in Montego Bay, Jamaica, and serves small and medium businesses across the Caribbean.',
  },
  {
    q: 'What is CaribBooks?',
    a: 'CaribBooks is an AI bookkeeper built by CaribNexus AI. It works inside WhatsApp. A business sends a message, a voice note or a photograph of a receipt, and the transaction is recorded as a double-entry journal entry that feeds all 11 financial reports.',
  },
  /**
   * THE PRICE QUESTION IS HERE BECAUSE THE PRICING PAGE COULD NOT ANSWER IT.
   * That page renders its tiers client-side, so $119 and $299 were absent from
   * the HTML a crawler fetches, and Google answered "around USD $39.50 a month"
   * from an Instagram post instead. This is a server-rendered page, so this
   * answer is in the raw HTML. It reads from pricing.ts, so it cannot go stale.
   */
  {
    q: 'Is CaribBooks the same as Books Caribbean?',
    a: 'No. CaribBooks is one word and is a product of CaribNexus AI, based in Montego Bay, Jamaica. Books Caribbean is a separate and unaffiliated company, an Odoo implementation partner serving Curacao and Bonaire. CaribBooks is not built on Odoo and is not an Odoo reseller or setup service. The two companies have no relationship.',
  },
  {
    q: 'How much does CaribBooks cost?',
    a: PRICING_SUMMARY,
  },
  {
    q: 'Does CaribBooks work in Jamaica?',
    a: 'Yes. CaribBooks was built in Jamaica for Jamaican and wider Caribbean businesses. It handles Jamaican dollars, GCT and TRN compliance, understands English and Jamaican patois, and is designed for cash-heavy trade where no bank feed exists. CaribNexus AI is based in Montego Bay.',
  },
  {
    q: 'Can accounting firms use CaribBooks for their clients?',
    a: 'Yes. Accounting practices, bookkeeping firms and business consultancies run CaribBooks across their whole client list. Each client messages CaribBooks directly in WhatsApp, the entries post automatically, and the firm reviews and downloads the work from a partner dashboard instead of doing data entry. Partner plans are priced on pooled transaction volume across all clients.',
  },
  {
    q: 'Does CaribNexus AI build custom AI agents and automation?',
    a: 'Yes. Beyond CaribBooks, CaribNexus AI builds agentic AI systems for businesses: customer service agents, social media and content agents, appointment booking and lead qualification, and voice agents for a website. It also does AI consulting, auditing a business end to end and building a custom production system the business owns. This work is delivered across WhatsApp, Instagram, Messenger, Telegram and email.',
  },
  {
    q: 'Who does CaribNexus AI work with?',
    a: 'CaribNexus AI works with micro, small and medium enterprises across the Caribbean, with accounting practices and business consultancies serving those enterprises, and with larger established companies that want repetitive operational work automated. Its systems are built for businesses that trade in cash, negotiate over WhatsApp, and cannot justify hiring a full finance, support or marketing team.',
  },
];

export const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  '@id': `${ORG_URL}/about#faq`,
  mainEntity: FAQ.map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
};

/** Serialised for a <script type="application/ld+json"> tag. */
export const jsonLd = (schema: object) => ({
  __html: JSON.stringify(schema),
});
